### ISSUE TITLE
line-anim is missing

### ISSUE THREAD

**Issue by JerryI** [CianLM/reveal-animated-latex#2]
Hey, I tried it to run, but what I see is just a blank white screen.
Checking styles, it seems you are referring to `line-anim` and `fill` animations, which are not defined anywhere...

**Comment by JerryI** [comment]
oki I found it on your blog page, thanks God you have it ;)

```
@keyframes line-anim {
    to {
        stroke-dashoffset: 0
    }
}

@keyframes fill {
    0% {
        fill: transparent
    }

    to {
        fill: currentColor;
        stroke-width: 0px
    }
}
```

**Comment by CianLM** [comment]
Thanks! Should be fixed now.
